routes/web.php
<?php

use App\Http\Livewire\AccessController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware(['auth'])->group( function() {
    Route::view('home',             'home')->name('home');
    Route::view('users',            'users')->name('users');

    Route::get('handle/pdf',        [AccessController::class, 'handlePDF'])->name('pdf');

});

app/Models/Employee.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'employees';

    const ACTIVE = 'ACTIVO';


    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'document_number',
        'department_id',
        'status'
    ];

    public function department() {
        return $this->belongsTo(Department::class,'department_id');
    }

    public function accessActions() {
        return $this->hasMany(AccessAction::class);
    }

    // scope
    public function scopeHandleAll($query)
    {
        return $query->where('id', '>', 0);
    }

    public function scopeSearch($query, $search)
    {
        return $query->where('first_name','like', '%'.$search.'%')
                        ->orWhere('id','like', '%'.$search.'%')
                        ->orWhere('middle_name','like', '%'.$search.'%')
                        ->orWhere('last_name','like', '%'.$search.'%')
                        ->orWhere('document_number','like', '%'.$search.'%')
                        ->orWhere('last_name','like', '%'.$search.'%')
                        ->orWhere('status','like', '%'.$search.'%');
    }

    public function scopeDocumenNumber($query, $document){
        return $query->where('document_number', $document);
    }

    public function scopeDepartment($query, $id){
        return $query->where('department_id', $id);
    }

    public function scopeDateAccess($query, $dateFrom, $dateTo){
        return $query->whereHas('accessActions', function($q) use ($dateFrom, $dateTo){
            $q->whereDate('created_at', '>=', $dateFrom);
            $q->whereDate('created_at', '<=', $dateTo);
            $q->where('success', 'YES');
        });
    }

    public function scopeUniqueDateAccess($query, $date){
        return $query->whereHas('accessActions', function($q) use ($date){
            $q->whereDate('created_at', $date);
            $q->where('success', 'YES');
        });
    }

    //  ACCESSORS
    public function getFirstNameAttribute($value) {
        return ucfirst($value);
    }

    public function getLastNameAttribute($value) {
        return ucfirst($value);
    }

    public function getMiddleNameAttribute($value) {
        return ucfirst($value);
    }

    public function getFullNameAttribute() {
        return $this->first_name.' '.$this->middle_name.' '.$this->last_name;
    }

    public function getLastAccessAttribute() {
        $access = AccessAction::where('employee_id', $this->id)->where('success', 'YES')->get()->last();
        if ($access) {
            return Carbon::parse($access->created_at)->toFormattedDateString().' - '.Carbon::parse($access->created_at)->format('h:i:s A');
        }
        return 'not record';
    }

    public function getLastAccessTotalAttribute() {
        return AccessAction::where('employee_id', $this->id)->where('success', 'YES')->count();
    }

    public function getFullCreatedAtAttribute() {
        return Carbon::parse($this->created_at)->toFormattedDateString().' - '.Carbon::parse($this->created_at)->format('h:i:s A');
    }

    public function getFullUpdatedAtAttribute() {
        return Carbon::parse($this->updated_at)->toFormattedDateString().' - '.Carbon::parse($this->updated_at)->format('h:i:s A');
    }

}

app/Http/Livewire/AccessController.php
<?php

namespace App\Http\Livewire;

use App\Imports\EmployeeImport;
use App\Models\AccessAction;
use App\Models\Department;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;
use Livewire\Component;
use Livewire\WithPagination;
use Maatwebsite\Excel\Facades\Excel;
use Livewire\WithFileUploads;
use PDF ;

class AccessController extends Component
{
    use WithPagination, WithFileUploads;

    protected $paginationTheme = 'bootstrap';//be able to use pagination in laravel 8


    public $selected_id, $search, $action = 1, $count = 1, $edit = 1, $url;
    public $employee, $first_name, $middle_name, $last_name, $document_number, $department = 'Elegir', $status = 'ACTIVE';
    public $departments, $accessEmployee, $csvFile;
    public $dateFromFilter, $dateToFilter, $departmentFilter = 'Elegir', $dateFromFilterShow, $dateToFilterShow;
    public $pagination = 10;

    public function mount(){
        $this->departments  = Department::active()->orderBy('name')->get();
        $this->url          = Route::current()->getName();
    }

    public function render()
    {
        try {
            $employees = Employee::handleAll();

            return view('livewire.employees.component',[
                'info'  => $this->handleFilter($employees)->orderBy('id','asc')->paginate($this->pagination),
            ]);

        } catch (\Exception $e) {
           return $e;
        }
    }

    public function handleAction($action)
    {
        $this->handleReset($action);
    }

    public function StoreOrUpdate($action)
    {
        $this->validate([
                'first_name'                => 'bail|required|min:3|max:20|string',
                'middle_name'               => 'bail|nullable|string|min:3|max:50',
                'last_name'                 => 'bail|required|string|min:3|max:50',
                'document_number'           => 'bail|required|numeric|digits_between:7,12|unique:employees,document_number,'.$this->selected_id,
                'department'                => 'bail|required|not_in:Elegir',
            ]
        );

        $find = [
            'id'  => $this->selected_id,
        ];
        $data = [
            'first_name'            => $this->first_name,
            'last_name'             => $this->last_name,
            'middle_name'           => $this->middle_name ? $this->middle_name : null,
            'document_number'       => $this->document_number,
            'department_id'         => $this->department,
        ];

        // dd($data);
        $employee = Employee::updateOrCreate($find, $data);


        if ($this->selected_id) {
            $updateOrCreate = 'update';
        }else{
            $updateOrCreate = 'created';
        }
        $this->handleReset($action);
        $this->emit('modalsClosed');//emit to js closed modals
        $this->emit('msgok','Employee '.$employee->first_name.', to '.$updateOrCreate);

    }

    // listen for events and execute requested action
    protected $listeners = ['handleState','deleteEmployee'];

    public function handleState(Employee $employe, $status, $action ){
        $employe->status = $status;
        $employe->save();
        $this->handleReset($action);
    }

    public function deleteEmployee(Employee $employe, $action ){
        $employe->delete();
        $this->handleReset($action);
    }

    public function accessEmployee($action){
        if ($this->document_number) {
            $employee = Employee::documenNumber($this->document_number)->first();
            if ($employee) {
                if ($employee->status == 'ACTIVE') {
                    $data = [
                        'employee_id'   => $employee->id,
                        'success'       => 'YES',
                    ];
                    $this->emit('msgok','Access Successful');
                }else{
                    $data = [
                        'employee_id'   => $employee->id,
                    ];
                    $this->emit('msg-error','Employee are DISABLED');
                }

            }else{
                $data = [
                    'document_number'   => $this->document_number,
                ];
                $this->emit('msg-error','Employee does not exist');
            }
            AccessAction::create($data);
            $this->emit('modalsClosed');//emit to js closed modals
            $this->handleReset($action);
        }else{
            $this->emit('msg-error','document number required');
        }

    }

    public function edit(Employee $user, $action)
    {
    	$this->employee             = $user;
    	$this->selected_id          = $user->id;
    	$this->first_name           = $user->first_name;
    	$this->last_name            = $user->last_name;
    	$this->middle_name          = $user->middle_name;
    	$this->document_number      = $user->document_number;
    	$this->department           = $user->department_id;
        $this->accessEmployee       = $user->accessActions;
    	$this->action               = $action;
    	$this->edit                 = 2;
    }

    public function handleReset($action)
    {
        $this->first_name           = '';
        $this->last_name            = '';
        $this->middle_name          = '';
        $this->search               = '';
        $this->document_number      = '';
        $this->department           = '';
        $this->dateFromFilter       = '';
        $this->dateToFilter         = '';
        $this->dateFromFilterShow   = '';
        $this->dateToFilterShow     = '';
        $this->accessEmployee       = '';
        $this->csvFile              = '';
        $this->count                = 1;
        $this->edit                 = 1;
        $this->action               = $action;
        $this->selected_id          = null;
        $this->department           = 'Elegir';
        $this->departmentFilter     = 'Elegir';
        $this->status               = 'ACTIVO';
    }

    public function updatingSearch(){
        $this->gotoPage(1);
    }

    public function handleAccessDate($action){
        $access = AccessAction::getAccesEmployye($this->selected_id);

        if ($this->dateFromFilterShow && $this->dateToFilterShow ) {
            $access->dateAccess($this->dateFromFilterShow, $this->dateToFilterShow);
        }else{
            if ($this->dateFromFilterShow) {
                $access->uniqueDateAccess($this->dateFromFilterShow);
            }
            if ($this->dateToFilterShow) {
                $access->uniqueDateAccess($this->dateToFilterShow);
            }
        }
        $this->accessEmployee   = $access->get();
        $this->action           = $action;
    }

    public function handlePDF(){
        $access = AccessAction::all();
        $date   = Carbon::now()->format('y-m-d - h:i:s');
        $pdf    = PDF::loadView('historyPDF',compact('access', 'date'));
        return $pdf->stream("access-history-{$date}.pdf");
    }

    public function createEmployeeCSV($action){
        if ($this->csvFile) {
            if ($this->csvFile->extension() == 'xlsx' || $this->csvFile->extension() == 'csv') {
                (new EmployeeImport)->import($this->csvFile);
                $this->emit('msgok','Successfull File csv');
                $this->emit('modalsClosed');//emit to js closed modals
                $this->handleReset($action);
            }else{
                $this->emit('msg-error','Unsupported file');
            }
        }else{
            $this->emit('msg-error','File csv not exist');
        }
    }

    public function handleFilter($employee){
        if ($this->search) {
            $employee->search($this->search);
        }
        if ($this->departmentFilter != 'Elegir') {
            $employee->department($this->departmentFilter);
        }

        if ($this->dateFromFilter && $this->dateToFilter ) {
            $employee->dateAccess($this->dateFromFilter, $this->dateToFilter);
        }else{
            if ($this->dateFromFilter) {
                $employee->uniqueDateAccess($this->dateFromFilter);
            }
            if ($this->dateToFilter) {
                $employee->uniqueDateAccess($this->dateToFilter);
            }
        }

        return $employee;
    }
}

app/Http/Livewire/UserController.php
<?php

namespace App\Http\Livewire;

use App\Models\Role;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Livewire\Component;
use Livewire\WithPagination;
use Illuminate\Support\Facades\Auth;

class UserController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';//poder utilizar la paginación en laravel 8


    public $roles, $selected_id, $user, $name, $email, $user_name, $password, $role = 'Elegir', $status ='ACTIVE', $search, $action = 1, $edit = 1;
    public $pagination = 5;
    public $newPassword, $repeatNewPassword;

    public function mount(){
        $this->roles    = Role::active()->get();
        $this->url      = Route::current()->getName();

    }

    public function render()
    {
        $users = User::handleAll();
        if (Auth::user()->role->name != "Admin ROOM_911") {
            $users = $users->authUser(Auth::user()->id);
        }
        if ($this->search) {
            $users->Search($this->search);
        }
        return view('livewire.users.component',[
            'info'  => $users->orderBy('name')->paginate($this->pagination),
        ]);
    }

    public function handleAction($action)
    {
        $this->handleReset($action);
    }

    public function StoreOrUpdate($action)
    {
        // dd($this->status);
        $this->validate([
                'name'                => 'bail|required|min:3|max:20|string',
                'email'               => 'bail|required|email|min:3|max:100',
                'password'            => 'bail|required|string',
                'user_name'           => 'bail|required|string|min:3|max:50|unique:users,user_name,'.$this->selected_id,
                'role'                => 'bail|required|not_in:Elegir',
                'status'              => 'bail|required|not_in:Elegir',
            ]
        );

        $find = [
            'id'  => $this->selected_id,
        ];
        $data = [
            'name'            => $this->name,
            'email'           => $this->email,
            'user_name'       => $this->user_name,
            'role_id'         => $this->role,
            'status'          => $this->status,
        ];


        if ($this->selected_id) {
            $updateOrCreate = 'update';
        }else{
            $updateOrCreate     = 'created';
            $data['password']   = Hash::make($this->password);
        }

        $user = User::updateOrCreate($find, $data);

        $this->handleReset($action);
        $this->emit('modalsClosed');//emit to js closed modals
        $this->emit('msgok','User '.$user->name.', to '.$updateOrCreate);

    }

    public function handlePassword(User $user, $action){
        if ($this->newPassword) {
            if ($this->newPassword == $this->repeatNewPassword) {
                $user->update([
                    'password' => Hash::make($this->newPassword)
                ]);
                $this->emit('modalsClosed');
                $this->emit('msgok','User '.$user->name.', changed password');
                $this->handleReset($action);
            }else{
                $this->emit('msg-error','Passwords do not match');
            }
        }else{
            $this->emit('msg-error','Incorrect value, please enter a password');
        }
    }

    public function clearPasswords(){
        $this->newPassword          = null;
        $this->repeatNewPassword    = null;
    }

    // listen for events and execute requested action
    protected $listeners = ['handleState','deleteUser'];

    public function handleState(User $user, $status, $action ){
        $user->status = $status;
        $user->save();
        $this->handleReset($action);
    }

    public function deleteUser(User $user, $action ){
        $user->delete();
        $this->handleReset($action);
    }

    public function edit(User $user, $action)
    {
    	$this->user                 = $user;
    	$this->selected_id          = $user->id;
    	$this->name                 = $user->name;
    	$this->email                = $user->email;
    	$this->password             = $user->password;
    	$this->role                 = $user->role_id;
    	$this->user_name            = $user->user_name;
    	$this->status               = $user->status;
    	$this->action               = $action;
    	$this->edit                 = 2;
    }

    public function handleReset($action)
    {
        $this->name                 = '';
        $this->user                 = '';
        $this->email                = '';
        $this->search               = '';
        $this->role                 = '';
        $this->user_name            = '';
        $this->password             = '';
        $this->edit                 = 1;
        $this->action               = $action;
        $this->selected_id          = null;
        $this->newPassword          = null;
        $this->repeatNewPassword    = null;
        $this->role                 = 'Elegir';
        $this->status               = 'ACTIVE';
    }

    public function updatingSearch(){
        $this->gotoPage(1);
    }
}

resources/views/livewire/employees/component.blade.php
<div class="row layout-top-spacing">
    <div class="col-xl-12 col-lg-12 col-md-12 col-12 layout-spacing">
        @if($action == 1)
            <div class="widget-content-area br-4">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 text-center">

                            <h5><b>Access ROOM_911</b></h5>

                        </div>
                    </div>
                </div>
                @include('common.search')
                @include('livewire.employees.filter')
                @include('common.alerts')
                @if ($info->count() > 0)
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped table-checkable table-highlight-head mb-4">
                            <thead>
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Department</th>
                                    <th class="text-center">Last Name</th>
                                    <th class="text-center">Middle Name</th>
                                    <th class="text-center">Firts Name</th>
                                    <th class="text-center">Document Number</th>
                                    <th class="text-center">Status Access</th>
                                    <th class="text-center">Last Access</th>
                                    <th class="text-center">Total Access</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($info as $elemen)
                                    <tr>
                                        <td class="text-center">{{$elemen->id}}</td>
                                        <td class="text-center">{{$elemen->department->name}}</td>
                                        <td class="text-center">{{$elemen->last_name}}</td>
                                        <td class="text-center">{{$elemen->middle_name ? $elemen->middle_name:'empty...'}}</td>
                                        <td class="text-center">{{$elemen->first_name}}</td>
                                        <td class="text-center">{{$elemen->document_number}}</td>
                                        <td class="text-center">{{$elemen->status}}</td>
                                        <td class="text-center">{{$elemen->last_access }}</td>
                                        <td class="text-center">{{$elemen->last_access_total }}</td>

                                        <td class="text-center" style="width: 30%">
                                            @include('common.actions')
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{$info->links()}}
                    </div>
                @else
                    <h5 class="text-center mb-4">No Records...</h5>
                @endif
            </div>

        @elseif($action == 2)
            @include('livewire.employees.show')
        @endif
    </div>
    @include('livewire.employees.modals')
</div>

<script type="text/javascript" src="{{ asset('js/employees/employee.js') }}"></script>

resources/views/livewire/employees/filter.blade.php
<div class="row justify-content-start mb-4 mt-3">
	<div class="col-lg-2 col-md-2 col-sm-8">
        <label >Department</label>
        <select wire:model="departmentFilter"  class="form-control">
            <option value="Elegir">Elegir</option>
            @foreach($departments as $department)
                <option value="{{ $department->id }}" >
                    {{ $department->name}}
                </option>
            @endforeach
        </select>
    </div>
    <div class="col-lg-3 col-md-2 col-sm-8">
        <label >Initial access date</label>
        <input wire:model.lazy="dateFromFilter" type="date" class="form-control">
    </div>
    <div class="col-lg-3 col-md-2 col-sm-8">
        <label >Final access date</label>
        <input wire:model.lazy="dateToFilter" type="date" class="form-control">
    </div>
</div>

resources/views/livewire/employees/show.blade.php
<div class="widget-content-area ">
    <div class="widget-header">
        <div class="row">
            <div class="col-xl-12 text-center">
                <h5><b>Employee Information</b></h5>
            </div>
        </div>
    </div>
    <div class="widget-one">
        <div class="row">
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Full Name</label>
                <h6 class=""><b>{{$employee->full_name}}</b></h6>
            </div>

            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Document Number</label>
                <h6 class=""><b>{{$employee->document_number}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Department</label>
                <h6 class=""><b>{{$employee->department->name}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Status Access</label>
                <h6 class=""><b>{{$employee->status}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Last Access</label>
                <h6 class=""><b>{{$employee->last_access}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Total Access</label>
                <h6 class=""><b>{{$employee->last_access_total}}</b></h6>
            </div>

            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Created at</label>
                <h6 class=""><b>{{$employee->full_created_at}}</b></h6>
            </div>

            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Update at</label>
                <h6 class=""><b>{{$employee->full_updated_at}}</b></h6>
            </div>
        </div>
    </div>
    <div class="widget-header">
        <div class="row">
            <div class="col-xl-12 text-center">
                <h5><b>History access ROOM_911</b></h5>
            </div>
        </div>
    </div>
    <div class="row justify-content-start mb-4 mt-3">
        <div class="col-lg-3 col-md-2 col-sm-8">
            <label >Initial access date</label>
            <input wire:model="dateFromFilterShow" wire:change="handleAccessDate(2)"  type="date" class="form-control">
        </div>
        <div class="col-lg-3 col-md-2 col-sm-8">
            <label >Final access date</label>
            <input wire:model="dateToFilterShow" wire:change="handleAccessDate(2)" type="date" class="form-control">
        </div>
    </div>
    @if ($accessEmployee->count())
        @foreach ($accessEmployee as $access)
            <div class="widget-one">
                <div class="row">
                    <div class="form-group col-lg-4 col-md-4 col-sm-12">
                        <label >Access</label>
                        <h6 class=""><b>{{$access->full_created_at}}</b></h6>
                    </div>
                    <div class="form-group col-lg-4 col-md-4 col-sm-12">
                        <label >Success</label>
                        <h6 class=""><b>{{$access->success}}</b></h6>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <div class="widget-header">
            <div class="row">
                <div class="col-xl-12 text-center">
                    <h6><b>No records...</b></h6>
                </div>
            </div>
        </div>
    @endif


    <div class="row ">
        <div class="col-lg-5 mt-2  text-left">
            <button type="button" wire:click="handleAction(1)" class="btn btn-dark mr-1">
                <i class="mbri-left"></i> Exit
            </button>
        </div>
    </div>
</div>